version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: adoption-mysql
    environment:
      MYSQL_DATABASE: adoptionProject
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - adoption-net

  app:
    build: .
    container_name: adoption-app
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/adoptionProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - adoption-net

volumes:
  mysql-data:

networks:
  adoption-net:
